[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "Wavelink"
version = "2.0.0b1"
authors = [
  { name="EvieePy", email="evieepy@gmail.com" },
]
dynamic = ["dependencies"]
description = "A robust and powerful Lavalink wrapper for discord.py"
readme = "README.rst"
requires-python = ">=3.10"
classifiers = [
        "License :: OSI Approved :: MIT License",
        "Intended Audience :: Developers",
        "Natural Language :: English",
        "Operating System :: OS Independent",
        "Programming Language :: Python :: 3.10",
        "Programming Language :: Python :: 3.11",
        "Topic :: Internet",
        "Topic :: Software Development :: Libraries",
        "Topic :: Software Development :: Libraries :: Python Modules",
        "Topic :: Utilities",
]

[project.urls]
"Homepage" = "https://github.com/PythonistaGuild/Wavelink/tree/2.0"

[tool.setuptools.dynamic]
dependencies = {file = ["requirements.txt"]}

[tool.poetry.group.docs]
optional = true

[tool.poetry.group.docs.dependencies]
sphinx="5.3.0"
docutils="0.17.1"
sphinxcontrib-napoleon="0.7"
sphinxcontrib-asyncio="0.3.0"
sphinxcontrib-websupport="1.2.4"
Pygments="2.14.0"
furo="2022.12.7"
discord.py="^2.1.0"